### ISSUE TITLE
Crash in TRTRewards WheelView

### ISSUE THREAD

**Issue by mkassoff** [Clinkle/TRTRewards-ios#1]
We are getting quite a few of these crashes (100% on iPad):

Could not cast value of type 'TRTRewards.TRTWheelView' (0xe1f518) to 'TRTRewards.TRTWheelImageView' (0xe1f4a8).

Thread : Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x34504c84 __pthread_kill + 8
1  libsystem_pthread.dylib        0x345a8733 pthread_kill + 62
2  libsystem_c.dylib              0x3449cf21 abort + 108
3  libswiftCore.dylib             0x1569fff swift::fatalError(char const*, ...) + 82
4  libswiftCore.dylib             0x154e4a5 swift::swift_dynamicCastFailure(swift::Metadata const*, swift::Metadata const*, char const*) + 70
5  libswiftCore.dylib             0x154e50d swift_dynamicCastClass + 102
6  libswiftCore.dylib             0x154e555 swift_getDynamicType + 38
7  TRTRewards                     0xde8818 _TFC10TRTRewards12TRTWheelViewgP33_2884C3358C750F3E3DAE3D26F1D406AC15nextFrameOffsetV12CoreGraphics7CGFloat + 676
8  TRTRewards                     0xdea668 _TFC10TRTRewards12TRTWheelView6scrollfS0_FT_T_ + 28
9  TRTRewards                     0xdeaabc _TToFC10TRTRewards12TRTWheelView6scrollfS0_FT_T_ + 24
10 QuartzCore                     0x25cb17f3 CA::Display::DisplayLinkItem::dispatch() + 106
11 QuartzCore                     0x25cb163f CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 594
12 IOMobileFramebuffer            0x2bb8f57b IOMobileFramebufferVsyncNotifyFunc + 86
13 IOKit                          0x233684d9 IODispatchCalloutFromCFMessage + 256
14 CoreFoundation                 0x2225e059 __CFMachPortPerform + 132
15 CoreFoundation                 0x222703b3 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 34
16 CoreFoundation                 0x2226fac7 __CFRunLoopDoSource1 + 342
17 CoreFoundation                 0x2226ded9 __CFRunLoopRun + 1688
18 CoreFoundation                 0x221c1119 CFRunLoopRunSpecific + 520
19 CoreFoundation                 0x221c0f05 CFRunLoopRunInMode + 108
20 GraphicsServices               0x2b34bac9 GSEventRunModal + 160
21 UIKit                          0x26403f15 UIApplicationMain + 144
22 Tophatter                      0xa8c33 main (main.m:3)
23 libdyld.dylib                  0x34435873 start + 2

**Comment by alberteloyan** [comment]
This is old and who are you?

**Comment by alberteloyan** [comment]
Resolved in v3.0
Thanks for the report!
